// <auto-generated />
using System;
using Especialidad.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220622171534_iteachDB")]
    partial class iteachDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClassItem.ClassItems", b =>
                {
                    b.Property<int>("IdClass")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameEnroll")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameModule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameSemester")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("IdClass");

                    b.ToTable("ClassItem");
                });

            modelBuilder.Entity("EnrollmentItem.EnrollmentItems", b =>
                {
                    b.Property<int>("IdEnroll")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EspModule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameEnrole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameModule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("IdEnroll");

                    b.ToTable("EnrollmentItem");
                });

            modelBuilder.Entity("ModuleItem.ModuleItems", b =>
                {
                    b.Property<int>("IdModule")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EspModule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameModule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("IdModule");

                    b.ToTable("ModuleItem");
                });

            modelBuilder.Entity("TaskItem.TaskItems", b =>
                {
                    b.Property<int>("IdTask")
                        .HasColumnType("int");

                    b.Property<string>("EspModule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameModule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameTask")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("ScoreTask")
                        .HasColumnType("int");

                    b.HasKey("IdTask");

                    b.ToTable("TaskItem");
                });

            modelBuilder.Entity("UsersItem.UserItems", b =>
                {
                    b.Property<int>("IdModule")
                        .HasColumnType("int");

                    b.Property<int>("DniUser")
                        .HasColumnType("int");

                    b.Property<string>("EmailUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdClass")
                        .HasColumnType("int");

                    b.Property<int>("IdEnroll")
                        .HasColumnType("int");

                    b.Property<int>("IdTask")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SurnameUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("IdModule");

                    b.ToTable("UserItem");
                });
#pragma warning restore 612, 618
        }
    }
}
